import { Schema, model, Document } from "mongoose";
import { ModificationSchema, IModification } from "../../core";

// Base Machine interface (for creating/updating)
export interface Machine {
  machineId: string; // Unique identifier generated by the client app
  computerName: string;
  operatingSystem: string;
  operatingSystemVersion: string;
  operatingSystemArchitecture: string;
  operatingSystemDescription: string;
  domainName?: string;
  workgroup?: string;
  isActive: boolean;
  lastSeen?: Date;
  description?: string;
  location?: string;
  owner?: string;
}

// Machine with database ID
export interface IMachine extends Machine {
  id: string;
}

// Machine Mongoose Document
export interface IMachineDB extends Document, Machine, IModification {}

// Machine Schema
const MachineSchema = new Schema<IMachineDB>(
  {
    machineId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    computerName: {
      type: String,
      required: true,
    },
    operatingSystem: {
      type: String,
      required: true,
    },
    operatingSystemVersion: {
      type: String,
      required: true,
    },
    operatingSystemArchitecture: {
      type: String,
      required: true,
    },
    operatingSystemDescription: {
      type: String,
      required: true,
    },
    domainName: {
      type: String,
    },
    workgroup: {
      type: String,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    lastSeen: {
      type: Date,
      default: Date.now,
    },
    description: {
      type: String,
    },
    location: {
      type: String,
    },
    owner: {
      type: String,
    },
  },
  { timestamps: true }
);

// Add modification tracking
MachineSchema.add(ModificationSchema);

const MachineDB = model<IMachineDB>("Machine", MachineSchema);

export default MachineDB;
